- name: mongodb module
  hosts: mongodb
  become: yes
  tasks:
  - name: mongodb copy
    ansible.builtin.copy:
        src: mongodb.repo
        dest: /etc/yum.repos.d/mongo.repo

  - name: installing mongodb-org
    ansible.builtin.dnf:
        name: mongodb-org
        state: latest

  - name: enabling mongodb
    ansible.builtin.service:
        name: mongod
        state: started
        enabled: yes

  - name: remote connections
    ansible.builtin.replace:
        path: /etc/mongod.conf
        regexp: 'bindIp:\s*127\.0\.0\.1'
        replace: 'bindIp: 0.0.0.0'

  - name: Restart MongoDB service
    ansible.builtin.service:
        name: mongod
        state: restarted
