- name: Nginx
  become: yes
  hosts: web
  tasks:
  - name: Installing nginx
    ansible.builtin.package:
      name: nginx
      state: present
  - name: running the nginx
    ansible.builtin.service:
      name: nginx
      state: started