- name: conditions
  hosts: localhost
  become: yes
  tasks:
  - name: creating roboshop user
    ansible.builtin.command: id roboshop
    register: user
    ignore_errors: true

  - name: print variable value
    ansible.builtin.debug:
      msg: "the output of user is {{user}}"

  - name: status
    ansible.builtin.debug:
      msg: "status of the user is {{user.rc}}"

  - name: Create user with when condition
    ansible.builtin.user:
      name: roboshop user
    when: user.rc!=0
